# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

  
  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
[[redirects]]
  from = "/studio/*"
  to = "/studio"
  status = 301
  # status = 307 = temporary redirect
  # status = 200 is working in production, but for APIs normally

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
